version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-pass}"
      POSTGRES_DB: "db"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"